project_id = "uziafykdgmibcpttagmr"

[functions.ai-chat]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.sync-meta-ads]
verify_jwt = false

[functions.sync-meta-leads]
verify_jwt = false

[functions.webhook-meta-leads]
verify_jwt = false

[functions.sync-instagram]
verify_jwt = false